"""
Consortium board generator.

Builds the Consortium map from the repository's own assets and pure geometry,
so no binary files need to be transferred. Run from the repository root:

    python3 tools/consortium-art/build_board.py

Requires Pillow only.

Produces:
    assets/board/mars_consortium.png     891x860 RGBA
    src/styles/board_positions.less      127 rules
    src/server/boards/consortiumSpaces.json

Geometry, derived from the existing Tharsis layout in
src/styles/board_items_positions.less:

    hex pitch   49 x 41 px
    hex asset   46 x 50 px
    field       634 x 542 px  (Tharsis is 441 x 378)

The board image is the game's own mars.png upscaled 1.44x with its grain
statistics preserved, so the Consortium map looks like it belongs beside
Tharsis, Hellas and Elysium rather than like a different game.

Artwork derives from the official Terraforming Mars asset sources,
CC BY-SA 4.0.
"""

import json
import math
import os
import sys
from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
MARS_SRC = os.path.join(ROOT, 'assets', 'board', 'mars.png')
MARS_DST = os.path.join(ROOT, 'assets', 'board', 'mars_consortium.png')
LESS_DST = os.path.join(ROOT, 'src', 'styles', 'board_positions.less')
JSON_DST = os.path.join(ROOT, 'src', 'server', 'boards', 'consortiumSpaces.json')

N = 6                       # map radius -> 3N^2+3N+1 = 127 spaces
CHASM_HALF = 45.0           # degrees of chasm arc either side of a bridge
SECTORS = [90.0, 210.0, 330.0]
PITCH_X, PITCH_Y = 49, 41
HEX_W, HEX_H = 46, 50

HIGHLANDS = [(0, -3), (1, -3), (0, -2), (-3, 1), (-3, 2), (-2, 1)]
CORE_CRATERS = [(4, -2), (-2, 4), (-2, -2)]


def ring(q, r):
    return (abs(q) + abs(r) + abs(q + r)) // 2


def axial_centre(q, r):
    return math.sqrt(3) * (q + r / 2.0), 1.5 * r


def bearing(q, r):
    x, y = axial_centre(q, r)
    return math.degrees(math.atan2(-y, x)) % 360


def arc_delta(a, b):
    d = abs(a - b) % 360
    return min(d, 360 - d)


def build_spaces():
    spaces = []
    for q in range(-N, N + 1):
        for r in range(-N, N + 1):
            if ring(q, r) <= N:
                spaces.append({'q': q, 'r': r, 'ring': ring(q, r)})

    for s in spaces:
        a = bearing(s['q'], s['r'])
        sector = min(range(3), key=lambda i: arc_delta(a, SECTORS[i]))
        near = arc_delta(a, SECTORS[sector]) <= CHASM_HALF
        s['sector'] = sector

        if s['ring'] <= 4:
            s['type'], s['zone'] = 'land', 'core'
        elif s['ring'] == 5:
            s['type'] = 'chasm' if near else 'land'
            s['zone'] = 'belt' if near else 'approach'
        else:
            s['type'], s['zone'] = 'land', 'frontier'
            s['locked'] = near
            s['bridge'] = sector

    for s in spaces:
        key = (s['q'], s['r'])
        if key in HIGHLANDS:
            s['type'] = 'highland'
        elif key in CORE_CRATERS:
            s['type'] = 'crater'

    for sector in range(3):
        candidates = sorted(
            (s for s in spaces
             if s['zone'] == 'frontier' and s['sector'] == sector
             and s['type'] == 'land'),
            key=lambda s: arc_delta(bearing(s['q'], s['r']), SECTORS[sector]))
        for s in candidates[:3]:
            s['type'] = 'crater'

    pts = [(s, *axial_centre(s['q'], s['r'])) for s in spaces]
    min_x = min(p[1] for p in pts)
    min_y = min(p[2] for p in pts)
    for i, (s, cx, cy) in enumerate(
            sorted(pts, key=lambda p: (round(p[2], 3), p[1])), start=1):
        s['id'] = i
        s['x'] = round((cx - min_x) / math.sqrt(3) * PITCH_X)
        s['y'] = round((cy - min_y) / 1.5 * PITCH_Y)

    return sorted(spaces, key=lambda s: s['id'])


def write_less(spaces):
    os.makedirs(os.path.dirname(LESS_DST), exist_ok=True)
    body = '\n'.join(
        f'.board-space-{s["id"]:03d} {{\n  margin: {s["y"]}px 0 0 {s["x"]}px;\n}}\n'
        for s in spaces)
    header = ('// Generated by tools/consortium-art/build_board.py\n'
              '// Do not edit by hand. Change the generator and rerun.\n\n')
    open(LESS_DST, 'w').write(header + body)


def write_json(spaces):
    os.makedirs(os.path.dirname(JSON_DST), exist_ok=True)
    with open(JSON_DST, 'w') as f:
        json.dump(spaces, f, indent=1)


def build_mars():
    if not os.path.exists(MARS_SRC):
        sys.exit(f'missing {MARS_SRC} - run from the repository root')

    src = Image.open(MARS_SRC).convert('RGBA')
    rgb, alpha = src.convert('RGB'), src.split()[3]

    residual = ImageChops.difference(rgb, rgb.filter(ImageFilter.GaussianBlur(1.2)))
    sigma = max(residual.convert('L').getextrema()[1] / 6.0, 6.0)

    tw = round(src.width * 634 / 441)
    th = round(src.height * 542 / 378)

    up = rgb.resize((tw, th), Image.LANCZOS)
    up = up.filter(ImageFilter.UnsharpMask(radius=1.6, percent=68, threshold=2))

    noise = Image.effect_noise((tw, th), sigma).filter(
        ImageFilter.GaussianBlur(0.4)).convert('L')
    grain = Image.merge('RGB', (noise, noise, noise))

    out = ImageChops.add(up, grain, scale=1.0, offset=-128).convert('RGBA')
    out.putalpha(alpha.resize((tw, th), Image.LANCZOS))
    out.save(MARS_DST)
    return out


def main():
    spaces = build_spaces()
    write_less(spaces)
    write_json(spaces)
    mars = build_mars()

    counts, zones = {}, {}
    for s in spaces:
        counts[s['type']] = counts.get(s['type'], 0) + 1
        zones[s['zone']] = zones.get(s['zone'], 0) + 1
    locked = sum(1 for s in spaces if s.get('locked'))

    field_w = max(s['x'] for s in spaces) + HEX_W
    field_h = max(s['y'] for s in spaces) + HEX_H

    print(f'spaces      : {len(spaces)}')
    print(f'by type     : {counts}')
    print(f'by zone     : {zones}')
    print(f'locked      : {locked}   open frontier: {zones["frontier"] - locked}')
    print(f'hex field   : {field_w} x {field_h} px')
    print(f'board image : {mars.size[0]} x {mars.size[1]} px  -> {MARS_DST}')
    print(f'css rules   : {len(spaces)}  -> {LESS_DST}')
    print(f'space data  : {JSON_DST}')


if __name__ == '__main__':
    main()
